version: "3.7"

services:
  api:
    build:
      context: api
      dockerfile: "Dockerfile"
      target: "${TARGET}"
    hostname: deno-api
    container_name: deno-api
    working_dir: "/app"
    environment:
      - "PORT=${API_PORT}"
      - "TARGET=${TARGET}"
    ports:
      - "${API_EX_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - ./volumes/deno-dir.${TARGET}:/deno-dir
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
    name: deno-network